### ISSUE TITLE
plz

### ISSUE THREAD

**Issue by RetracedFn** [Therealsxlar/9.41-Gameserver#1]
can u fix this u cant die i kill my self and is still saying 1 kid on the game and wont give win or smh

btw all work looting and all

you need add clientonpawndied for it

![image](https://github.com/user-attachments/assets/595a4f38-63bd-46e9-98f1-6e8b2d474cc1)

**Comment by Therealsxlar** [comment]
Working on it now

**Comment by RetracedFn** [comment]
Btw if u want add me discord i have a priv gs volcano 14.30 is working fine but amo box Crash on open and Loot is inproper ASF or buggy idk It have working Creative xp etc

**Comment by RetracedFn** [comment]
if u want to help if not all good
